package computerdatabase

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import scala.sys.process._

class HandsOnRequest extends Simulation {

  val httpConf = http
       .baseURL("http://localhost:3000/")  // edit here if you want to win!

  var jsonhead  = Map("Content-Type" -> "application/json; charset=utf-8")
  var hostname = Process("hostname -s").lineStream.toList
  var path =  hostname.head + "/tasks"

  val postScenario = scenario("request-POST")
        .exec( http("request-POST")
          .post(path)
          .headers(jsonhead)
          .body(StringBody("""{"item":"todo generated by gatling", "is_done": false}""")).asJSON
        )

  val getScenario = scenario("request-LIST")
        .exec(http("request-LIST")
          .get(path)
        )

  setUp(
    postScenario.inject( constantUsersPerSec(1) during(1 seconds) ).protocols(httpConf),
    getScenario.inject( constantUsersPerSec(40) during(60 seconds) ).protocols(httpConf)
  )
}

